.github/workflows/main.yml, backend/src/docs/asciidoc/index.adoc, backend/src/docs/asciidoc/school.adoc, backend/src/docs/asciidoc/user.adoc, backend/src/main/java/com/minibeit/school/dto/SchoolResponse.java, backend/src/main/java/com/minibeit/school/service/SchoolService.java, backend/src/main/java/com/minibeit/school/web/SchoolController.java, backend/src/main/java/com/minibeit/user/dto/UserResponse.java, backend/src/main/java/com/minibeit/user/service/UserService.java, backend/src/main/java/com/minibeit/user/web/UserController.java, backend/src/rest/SchoolController.http, backend/src/rest/UserController.http, backend/src/test/java/com/minibeit/school/web/SchoolControllerTest.java, backend/src/test/java/com/minibeit/user/web/UserControllerTest.java
=> [backend] 학교 전체 조회, 내정보 조회 구현, git action 연동

frontend/src/components/Login/LoginForm/PLoginForm.jsx, frontend/src/components/Login/LoginForm/index.jsx, frontend/src/components/Login/style.jsx, frontend/src/index.js, frontend/src/utils/auth.js
=> fix #10 dummylogin

backend/src/main/java/com/minibeit/security/oauth/OAuth2SuccessHandler.java, backend/src/main/resources/application.yml
=> [backend] 소셜로그인 response 변경 

frontend/src/components/ApplyDetail/FDTopContainer/PFDTopContainer.jsx, frontend/src/components/Common/SchoolModal.jsx, frontend/src/components/RecruitEdit/FEContainer/PFEContainer.jsx, frontend/src/components/RecruitEdit/FEContainer/index.jsx, frontend/src/components/SignupInfo/SignupInfoForm/PSignupInfoForm.jsx, frontend/src/components/SignupInfo/SignupInfoForm/index.jsx, frontend/src/pages/ProcessLogin/index.jsx, frontend/src/utils/feedApi.js
=> [frontend] signup login signupinfo

backend/src/main/java/com/minibeit/security/oauth/OAuth2Config.java, backend/src/main/resources/application.yml
=> [backend] Fix 회원가입시 학교 1개 선택하도록 수정, 소셜 로그인 수정

frontend/src/components/Profile/BProfileNew.jsx, frontend/src/components/Profile/BProfileNewModal.jsx, frontend/src/components/Profile/BProfileSection/PBProfileSection.jsx, frontend/src/components/Profile/BProfileSection/index.jsx, frontend/src/components/Profile/index.jsx, frontend/src/components/Profile/style.jsx, frontend/src/components/Recruit/FNContainer/PFNContainer.jsx, frontend/src/components/SignupInfo/SignupInfoForm/PSignupInfoForm.jsx, frontend/src/constants/API_URLS.js, frontend/src/pages/ProcessLogin/index.jsx, frontend/src/pages/Profile/index.jsx, frontend/src/utils/auth.js, frontend/src/utils/bprofileApi.js, frontend/src/utils/index.jsx
=> [frontend] business, 생성, 목록조회, 링크 

frontend/src/components/Common/LoadingSpinner.jsx, frontend/src/components/Common/index.jsx, frontend/src/components/Common/style.jsx, frontend/src/components/Login/LoginForm/PLoginForm.jsx, frontend/src/components/Profile/UserInfo/index.jsx, frontend/src/components/Signup/SignupForm/PSignupForm.jsx, frontend/src/components/SignupInfo/SignupInfoForm/index.jsx
=> [frontend] 로딩메시지 컴포넌트 & 구글 소셜로그인 구현

frontend/package.json, frontend/src/components/BProfile/BProfileInfo/PBProfile.jsx, frontend/src/components/BProfile/BProfileInfo/index.jsx, frontend/src/components/Profile/BProfileNewModal.jsx, frontend/src/components/Profile/BProfileSection/PBProfileSection.jsx, frontend/src/components/Profile/UserInfo/PUserInfo.jsx, frontend/src/components/SignupInfo/SignupInfoForm/PSignupInfoForm.jsx, frontend/src/pages/BProfile/index.jsx
=> [frontend] proptypes 적용

backend/src/main/java/com/minibeit/businessprofile/dto/BusinessProfileResponse.java, backend/src/main/java/com/minibeit/user/dto/UserResponse.java, backend/src/rest/UserController.http, backend/src/test/java/com/minibeit/businessprofile/web/BusinessProfileControllerTest.java, backend/src/test/java/com/minibeit/user/web/UserControllerTest.java
=> [backend] 비즈니스 프로필 단건 조회, 내정보 조회 수정

frontend/src/components/BProfile/BProfileInfo/PBProfile.jsx, frontend/src/components/BProfile/BProfileInfo/index.jsx, frontend/src/components/BProfile/style.jsx, frontend/src/components/BProfileEdit/BProfileEditCont/PBProfileEditCont.jsx, frontend/src/components/BProfileEdit/BProfileEditCont/index.jsx, frontend/src/components/BProfileEdit/style.jsx, frontend/src/components/Profile/BProfileNewModal.jsx, frontend/src/components/Profile/UserInfo/PUserInfo.jsx, frontend/src/components/Profile/style.jsx, frontend/src/utils/bprofileApi.js
=> [frontend ]business formdata( #36)

frontend/src/components/BProfile/BProfileInfo/PBProfile.jsx, frontend/src/components/BProfile/BProfileJoin/PBProfileJoin.jsx, frontend/src/components/BProfile/BProfileJoin/index.jsx, frontend/src/components/BProfile/style.jsx, frontend/src/constants/API_URLS.js, frontend/src/utils/bprofileApi.js, frontend/src/utils/index.jsx
=> [frontend] 비스니스 초대 api

backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/businessprofile/domain/repository/UserBusinessProfileRepository.java, backend/src/main/java/com/minibeit/common/component/file/RandomStringBuilder.java, backend/src/main/java/com/minibeit/common/component/file/S3Props.java, backend/src/main/java/com/minibeit/common/component/file/S3Uploader.java, backend/src/main/java/com/minibeit/file/service/FileService.java, backend/src/main/java/com/minibeit/post/domain/Payment.java, backend/src/main/java/com/minibeit/post/domain/Post.java, backend/src/main/java/com/minibeit/post/domain/PostDoDate.java, backend/src/main/java/com/minibeit/post/domain/PostFile.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepository.java, backend/src/main/java/com/minibeit/post/domain/repository/PostFileRepository.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepository.java, backend/src/main/java/com/minibeit/post/dto/PostFileDto.java, backend/src/main/java/com/minibeit/post/dto/PostRequest.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/main/java/com/minibeit/post/service/PostFileService.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/service/exception/PostNotFoundException.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/java/com/minibeit/user/domain/User.java, backend/src/main/resources/db/migration/V20210830150519__Create_Post_Table.sql, backend/src/main/resources/db/migration/V20210830150535__Create_Post_File_Table.sql, backend/src/main/resources/db/migration/V20210830160859__Create_Post_Do_Date_Table.sql, backend/src/rest/BusinessProfileController.http, backend/src/rest/PostController.http, backend/src/rest/UserController.http, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 게시물 생성, 단건조회, 삭제 구현 Feature/51

backend/src/docs/asciidoc/businessprofile.adoc, backend/src/docs/asciidoc/index.adoc, backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/post/domain/PostApplicant.java, backend/src/main/java/com/minibeit/post/domain/PostStatus.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepository.java, backend/src/main/java/com/minibeit/post/dto/PostRequest.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/service/exception/PostApplicantNotFoundException.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/resources/db/migration/V20210901134839__Create_Post_Applicant_Table.sql, backend/src/rest/BusinessProfileController.http, backend/src/rest/PostController.http, backend/src/rest/UserController.http, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 게시물 지원, 지원자 참여 결정 구현

backend/src/docs/asciidoc/businessprofile.adoc, backend/src/main/java/com/minibeit/businessprofile/service/BusinessProfileService.java, backend/src/main/java/com/minibeit/businessprofile/web/UserBusinessProfileController.java, backend/src/test/java/com/minibeit/businessprofile/web/UserBusinessProfileControllerTest.java
=> [backend] 공유 취소 기능 수정 

backend/src/docs/asciidoc/post.adoc
=> [backend] 게시물 목록 전체 조회(학교,날짜) 

frontend/src/components/BProfile/BProfileInfo/PBProfile.jsx, frontend/src/components/Common/Modal/CreateBProfileModal/index.jsx, frontend/src/components/Recruit/FNContainer/PFNContainer.jsx, frontend/src/utils/feedApi.js
#90 
이 이슈는 조건까지 다 구현하고 지우려고해서 우선 게시물 생성 비즈니스 생성 바뀐api로 작동하게 만들어 둔 부분이라 확인하시면 머지해 주시고 브랜치랑 이슈는 남겨주세요!
=> [frontend] 게시물 생성인원추가 , 비즈니스 카테고리삭제

backend/src/docs/asciidoc/post.adoc, backend/src/docs/asciidoc/user.adoc, backend/src/main/java/com/minibeit/businessprofile/domain/BusinessProfile.java, backend/src/main/java/com/minibeit/config/SecurityConfig.java, backend/src/main/java/com/minibeit/post/domain/Payment.java, backend/src/main/java/com/minibeit/post/domain/Post.java, backend/src/main/java/com/minibeit/post/domain/PostDoDate.java, backend/src/main/java/com/minibeit/post/domain/PostLike.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepository.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepositoryImpl.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostDto.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/main/java/com/minibeit/post/service/PostApplicantService.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/java/com/minibeit/user/dto/UserRequest.java, backend/src/main/java/com/minibeit/user/service/UserService.java, backend/src/main/java/com/minibeit/user/web/UserController.java, backend/src/main/resources/application.yml, backend/src/main/resources/db/migration/V20210830160859__Create_Post_Do_Date_Table.sql, backend/src/rest/AuthController.http, backend/src/rest/BusinessProfileController.http, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java, backend/src/test/java/com/minibeit/user/web/UserControllerTest.java
=> [backend] 게시물 조회 수정, 닉네임 중복확인 구현

frontend/src/components/BProfile/BProfileJoin/index.jsx, frontend/src/components/Common/NavBar/index.jsx, frontend/src/components/Profile/BProfileSection/PBProfileSection.jsx, frontend/src/components/Recruit/FNContainer/PFNContainer.jsx, frontend/src/components/Recruit/FNContainer/index.jsx, frontend/src/components/RecruitEdit/FEContainer/PFEContainer.jsx, frontend/src/components/RecruitEdit/FEContainer/index.jsx, frontend/src/components/SignupInfo/SignupInfoForm/index.jsx, frontend/src/utils/feedApi.js
=> [frontend] axios리팩토링 / recruit단계별 작업하다 맘

frontend/src/components/Apply/FilterAndList/PFilterContainer.jsx, frontend/src/components/Apply/FilterAndList/index.jsx, frontend/src/recoil/filterState.js, frontend/src/utils/feedApi.js
=> [frontend] api 맞춰 게시물 리스트 조회 수정

backend/src/docs/asciidoc/businessprofile.adoc, backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/businessprofile/domain/BusinessProfileReview.java, backend/src/main/java/com/minibeit/businessprofile/dto/BusinessProfileReviewResponse.java, backend/src/main/java/com/minibeit/businessprofile/dto/BusinessProfilesReviewRequest.java, backend/src/main/java/com/minibeit/businessprofile/service/BusinessProfileReviewService.java, backend/src/main/java/com/minibeit/businessprofile/service/BusinessProfileService.java, backend/src/main/java/com/minibeit/businessprofile/service/exception/BusinessProfileReviewNotFoundException.java, backend/src/main/java/com/minibeit/businessprofile/web/BusinessProfileController.java, backend/src/main/java/com/minibeit/businessprofile/web/BusinessProfileReviewController.java, backend/src/main/java/com/minibeit/config/SecurityConfig.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostRequest.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/resources/db/migration/V20210907142921__Create_Business_Profile_Review_Table.sql, backend/src/rest/AuthController.http, backend/src/rest/BusinessProfileReviewController.http, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/businessprofile/web/BusinessProfileReviewControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 후기 api 구현, post 리팩토링

frontend/src/components/Apply/FilterAndList/PBtnContainer.jsx, frontend/src/components/Apply/FilterAndList/PListContainer.jsx, frontend/src/components/Apply/FilterAndList/index.jsx, frontend/src/components/Apply/style.jsx, frontend/src/components/ApplyDetail/FeedInfoContainer/PFeedInfoContainer.jsx, frontend/src/components/ApplyDetail/FeedInfoContainer/PTimeSelectBox.jsx, frontend/src/components/ApplyDetail/FeedInfoContainer/index.jsx, frontend/src/components/Common/SchoolSearch/index.jsx, frontend/src/pages/ApplyDetail/index.jsx
=> [frontend] 상세페이지 쿼리스트링 & 게시물 리스트 페이징 처리

frontend/src/components/Apply/FilterAndList/PFilterContainer.jsx, frontend/src/components/Apply/FilterAndList/PListContainer.jsx, frontend/src/components/Apply/FilterAndList/index.jsx, frontend/src/components/Apply/style.jsx, frontend/src/components/ApplyDetail/FeedInfoContainer/PFeedInfoContainer.jsx, frontend/src/components/ApplyDetail/FeedInfoContainer/PTimeSelectBox.jsx, frontend/src/components/ApplyDetail/FeedInfoContainer/index.jsx, frontend/src/components/Common/Modal/ApplyConfirmModal/index.jsx, frontend/src/components/Common/Modal/ApplyConfirmModal/style.jsx, frontend/src/constants/API_URLS.js, frontend/src/recoil/applyState.js, frontend/src/utils/feedApi.js
=> [frontend] 지원하기 기능 구현 (#113)

frontend/src/components/BProfile/BProfileInfo/PBProfile.jsx, frontend/src/components/Common/FeedBox/BProfileFeed/index.jsx, frontend/src/components/Common/FeedBox/ProfileFeed/index.jsx, frontend/src/components/Common/FeedBox/style.jsx, frontend/src/components/Profile/JoinListBox/PJoinListBox.jsx, frontend/src/components/Profile/JoinListBox/index.jsx, frontend/src/components/Profile/ProfileCont/PProfileCont.jsx, frontend/src/components/Profile/style.jsx, frontend/src/components/SignupInfo/SignupInfoForm/PSignupInfoForm.jsx, frontend/src/components/SignupInfo/style.jsx, frontend/src/constants/API_URLS.js, frontend/src/utils/profileApi.js
=> [frontend] 게시물 컴포넌트화 

frontend/src/components/BProfile/BReviewBox/PBReviewBox.jsx, frontend/src/components/BProfile/BReviewBox/index.jsx, frontend/src/components/BProfile/BprofileContainer/index.jsx, frontend/src/components/BProfile/index.jsx, frontend/src/components/BProfile/style.jsx, frontend/src/components/Common/FeedBox/BProfileFeed/index.jsx, frontend/src/components/Common/FeedBox/ProfileFeed/index.jsx, frontend/src/components/Common/FeedBox/style.jsx, frontend/src/components/Common/ReviewModal/index.jsx, frontend/src/components/Common/ReviewModal/style.jsx, frontend/src/components/Profile/JoinListBox/PJoinListBox.jsx, frontend/src/components/Profile/JoinListBox/index.jsx, frontend/src/components/SignupInfo/SignupInfoForm/PSignupInfoForm.jsx, frontend/src/constants/API_URLS.js, frontend/src/pages/BProfile/index.jsx, frontend/src/utils/index.jsx, frontend/src/utils/profileApi.js, frontend/src/utils/reviewApi.js
=> [frontend] 후기 더보기 , 후기 리스트 , 후기 공통 컴포넌트화, 후기생성, 참여취소 +etc구현

backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 게시물 관심자 수 추가

backend/src/docs/asciidoc/businessprofile.adoc, backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/businessprofile/dto/BusinessProfileResponse.java, backend/src/main/java/com/minibeit/businessprofile/service/BusinessProfileService.java, backend/src/main/java/com/minibeit/businessprofile/web/BusinessProfileController.java, backend/src/main/java/com/minibeit/post/domain/Post.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepository.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/java/com/minibeit/user/domain/User.java, backend/src/rest/AuthController.http, backend/src/rest/BusinessProfileController.http, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/rest/UserController.http, backend/src/test/java/com/minibeit/businessprofile/web/BusinessProfileControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 비즈니스 프로필 단건조회, 초대 수정, 게시물 지원 조건 추가

frontend/src/components/BProfile/BMakeListBox/PBMakeListBox.jsx, frontend/src/components/BProfile/BMakeListBox/index.jsx, frontend/src/components/BProfile/BReviewBox/PBReviewBox.jsx, frontend/src/components/BProfile/BReviewBox/index.jsx, frontend/src/components/BProfile/BprofileContainer/index.jsx, frontend/src/components/BProfile/style.jsx, frontend/src/components/Profile/JoinListBox/PJoinListBox.jsx, frontend/src/components/Profile/JoinListBox/index.jsx, frontend/src/components/Profile/style.jsx, frontend/src/constants/API_URLS.js, frontend/src/utils/bprofileApi.js, frontend/src/utils/index.jsx, frontend/src/utils/reviewApi.js
=> [frontend] 페이징처리 + 비즈니스 프로필 게시물 완료

backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/post/domain/PostApplicant.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryImpl.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostApplicantDto.java, backend/src/main/java/com/minibeit/post/dto/PostApplicantRequest.java, backend/src/main/java/com/minibeit/post/dto/PostApplicantResponse.java, backend/src/main/java/com/minibeit/post/service/PostApplicantService.java, backend/src/main/java/com/minibeit/post/web/PostApplicantController.java, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/post/web/PostApplicantControllerTest.java
=> [backend] 게시물 대기자명단, 확정자 명단 구현, 비즈니스 프로필 완료한 실험 목록 조회 구현

frontend/package.json, frontend/src/components/BProfile/BMakeListBox/PBMakeListBox.jsx, frontend/src/components/BProfile/BMakeListBox/index.jsx, frontend/src/components/BProfile/BManageModal/index.jsx, frontend/src/components/BProfile/BManageModal/style.jsx, frontend/src/components/Common/FeedBox/BProfileFeed/index.jsx, frontend/src/constants/API_URLS.js, frontend/src/recoil/changeState.js, frontend/src/recoil/manageState.js, frontend/src/utils/bprofileApi.js, frontend/src/utils/feedApi.js, frontend/src/utils/index.jsx, frontend/yarn.lock
=> [frontend] 대기자, 확정자, 글내리기, 삭제하기

backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/MinibeitApplication.java, backend/src/main/java/com/minibeit/businessprofile/domain/BusinessProfileReview.java, backend/src/main/java/com/minibeit/businessprofile/service/BusinessProfileReviewService.java, backend/src/main/java/com/minibeit/businessprofile/web/BusinessProfileReviewController.java, backend/src/main/java/com/minibeit/post/domain/PostApplicant.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryImpl.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepositoryImpl.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/main/java/com/minibeit/post/scheduler/PostRejectScheduler.java, backend/src/main/java/com/minibeit/post/service/PostApplicantService.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/service/RejectPostService.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/java/com/minibeit/post/web/RejectPostController.java, backend/src/rest/AuthController.http, backend/src/rest/BusinessProfileReviewController.http, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/businessprofile/web/BusinessProfileReviewControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 게시물 목록 조회 조건 수정, 해당 게시물의 실험이 있는 날짜 목록 조회

frontend/src/components/BProfile/BMakeListBox/PBMakeListBox.jsx, frontend/src/components/BProfile/BManageModal/style.jsx, frontend/src/components/BProfile/BOtherProfile/PBOtherProfile.jsx, frontend/src/components/BProfile/BOtherProfile/index.jsx, frontend/src/components/BProfile/BProfileJoin/NicknameCombo.jsx, frontend/src/components/BProfile/BProfileJoin/PBProfileJoin.jsx, frontend/src/components/BProfile/BProfileJoin/index.jsx, frontend/src/components/BProfile/BProfileSection/PBProfileSection.jsx, frontend/src/components/BProfile/BReviewBox/PBReviewBox.jsx, frontend/src/components/BProfile/style.jsx, frontend/src/components/BProfileEdit/BCreateCont/index.jsx, frontend/src/components/BProfileEdit/BProfileEditCont/PBProfileEditCont.jsx, frontend/src/components/BProfileEdit/BProfileEditCont/index.jsx, frontend/src/components/BProfileEdit/style.jsx, frontend/src/components/Common/FeedBox/ProfileFeed/index.jsx, frontend/src/components/Common/ReviewModal/index.jsx, frontend/src/components/Profile/JoinListBox/PJoinListBox.jsx, frontend/src/components/Profile/JoinListBox/index.jsx, frontend/src/components/Profile/ProfileCont/PProfileCont.jsx, frontend/src/components/Profile/ProfileEditModal/PProfileEditModal.jsx, frontend/src/components/Profile/ProfileEditModal/index.jsx, frontend/src/components/Profile/UserInfo/PUserInfo.jsx, frontend/src/components/Profile/style.jsx, frontend/src/components/SignupInfo/SignupInfoForm/PSignupInfoForm.jsx, frontend/src/constants/API_URLS.js, frontend/src/pages/BProfile/style.jsx, frontend/src/utils/index.jsx, frontend/src/utils/profileApi.js, frontend/src/utils/reviewApi.js
=> [frontend] 중간머지용

backend/src/main/java/com/minibeit/businessprofile/service/BusinessProfileReviewService.java, backend/src/main/java/com/minibeit/post/domain/PostApplicant.java, backend/src/rest/AuthController.http, backend/src/rest/BusinessProfileReviewController.http, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/post/service/PostByBusinessServiceTest.java
=> [backend] 글내리기 버그 수정

backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 즐겨찾기 목록 Response 수정

frontend/src/components/BProfile/BManageModal/index.jsx, frontend/src/components/Common/Modal/ApplyConfirmModal/index.jsx, frontend/src/components/Common/ReviewModal/index.jsx, frontend/src/components/Recruit/CreateFeedContainer/PDateSelect.jsx, frontend/src/utils/bprofileApi.js, frontend/src/utils/feedApi.js, frontend/src/utils/reviewApi.js
=> [frontend] 시간 리스트, useEffect 삭제

backend/src/main/java/com/minibeit/businessprofile/domain/repository/BusinessProfileReviewRepositoryCustom.java, backend/src/main/java/com/minibeit/businessprofile/domain/repository/BusinessProfileReviewRepositoryImpl.java, backend/src/main/java/com/minibeit/businessprofile/dto/BusinessProfileReviewResponse.java, backend/src/main/java/com/minibeit/businessprofile/service/BusinessProfileReviewService.java, backend/src/main/java/com/minibeit/post/dto/PostDto.java, backend/src/main/java/com/minibeit/user/domain/repository/UserRepositoryCustom.java, backend/src/main/java/com/minibeit/user/domain/repository/UserRepositoryImpl.java, backend/src/main/java/com/minibeit/user/dto/UserResponse.java, backend/src/main/java/com/minibeit/user/service/UserService.java, backend/src/main/java/com/minibeit/user/web/UserController.java, backend/src/rest/AuthController.http, backend/src/rest/BusinessProfileReviewController.http, backend/src/rest/PostApplicantController.http, backend/src/rest/UserController.http, backend/src/test/java/com/minibeit/businessprofile/web/BusinessProfileReviewControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java, backend/src/test/java/com/minibeit/user/service/UserServiceTest.java, backend/src/test/java/com/minibeit/user/web/UserControllerTest.java
=> [backend] 게시물 단건조회, 리뷰 목록 조회 response data 추가

backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepository.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryImpl.java, backend/src/main/java/com/minibeit/post/service/PostApplicantByBusinessService.java, backend/src/main/java/com/minibeit/post/service/PostApplicantService.java, backend/src/rest/PostApplicantController.http, backend/src/test/java/com/minibeit/post/service/PostApplicantByBusinessFindServiceTest.java, backend/src/test/java/com/minibeit/post/service/PostApplicantByBusinessServiceTest.java, backend/src/test/java/com/minibeit/post/service/PostApplicantServiceTest.java, backend/src/test/java/com/minibeit/post/service/PostByBusinessFindServiceTest.java, backend/src/test/java/com/minibeit/post/service/PostServiceTest.java, backend/src/test/java/com/minibeit/post/service/RejectPostServiceTest.java, backend/src/test/java/com/minibeit/user/service/UserServiceTest.java
=> [backend] PostApplicant Service 통합테스트 작성

frontend/src/components/Apply/CategoryFilter/presenter.jsx, frontend/src/components/Apply/DetailFilter/presenter.jsx, frontend/src/components/Apply/SearchBar/index.jsx, frontend/src/components/Apply/SearchBar/presenter.jsx, frontend/src/components/Apply/index.jsx, frontend/src/components/Common/SchoolSelect/index.jsx, frontend/src/constants/FeedCategory.js, frontend/src/recoil/filterState.js, frontend/src/utils/feedApi.js
=> [frontend] 페이징, 필터 오류 수정

frontend/src/components/Common/NavBar/index.jsx, frontend/src/components/Common/NavBar/style.jsx, frontend/src/components/Recruit/BProfileSelect/presenter.jsx, frontend/src/components/Recruit/DateSelect/presenter.jsx, frontend/src/components/Recruit/InfoData/presenter.jsx, frontend/src/components/Recruit/SchoolSelect/index.jsx, frontend/src/components/Recruit/SchoolSelect/presenter.jsx, frontend/src/components/Recruit/index.jsx, frontend/src/components/Recruit/style.jsx
=> [frontend] 모집하기 예외추가

frontend/src/components/Apply/index.jsx, frontend/src/components/ApplyDetail/FeedInfoContainter/ReviewBox/index.jsx, frontend/src/components/ApplyDetail/FeedInfoContainter/TimeSelectBox/index.jsx, frontend/src/components/ApplyDetail/index.jsx, frontend/src/components/BProfile/BManageModal/index.jsx, frontend/src/components/BProfile/BProfileFeedList/index.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileEditModal/index.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileJoinModal/NicknameCombo.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileJoinModal/index.jsx, frontend/src/components/BProfile/BProfileInfo/index.jsx, frontend/src/components/BProfile/BProfileList/index.jsx, frontend/src/components/BProfile/BProfileMain/index.jsx, frontend/src/components/BProfile/BProfileReviewList/index.jsx, frontend/src/components/Common/FeedBox/BProfileFeed/index.jsx, frontend/src/components/Common/FeedBox/ProfileFeed/index.jsx, frontend/src/components/Common/Modal/RecruitConfirmModal/index.jsx, frontend/src/components/Common/Modal/SchoolSelectModal/index.jsx, frontend/src/components/Common/SchoolSearch/index.jsx, frontend/src/components/Common/SchoolSelect/index.jsx, frontend/src/components/Profile/JoinListBox/index.jsx, frontend/src/components/Profile/LikeListBox/index.jsx, frontend/src/components/Profile/UserInfoBox/ProfileEditModal/index.jsx, frontend/src/components/Profile/UserInfoBox/index.jsx, frontend/src/components/Recruit/index.jsx, frontend/src/components/SignupInfo/SignupInfoForm/index.jsx
=> [frontend] api맞춰 수정

backend/src/docs/asciidoc/auth.adoc, backend/src/docs/asciidoc/businessprofile.adoc, backend/src/docs/asciidoc/post.adoc, backend/src/docs/asciidoc/user.adoc, backend/src/main/java/com/minibeit/businessprofile/web/BusinessProfileController.java, backend/src/main/java/com/minibeit/businessprofile/web/BusinessProfileReviewController.java, backend/src/main/java/com/minibeit/common/advice/CustomExceptionHandler.java, backend/src/main/java/com/minibeit/common/advice/ErrorResponse.java, backend/src/main/java/com/minibeit/common/dto/ApiResult.java, backend/src/main/java/com/minibeit/post/web/PostApplicantByBusinessController.java, backend/src/main/java/com/minibeit/post/web/PostApplicantController.java, backend/src/main/java/com/minibeit/post/web/PostByBusinessController.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/java/com/minibeit/post/web/RejectPostController.java, backend/src/main/java/com/minibeit/school/web/SchoolController.java, backend/src/main/java/com/minibeit/user/web/AuthController.java, backend/src/main/java/com/minibeit/user/web/UserController.java, backend/src/rest/PostController.http, backend/src/rest/UserController.http, backend/src/test/java/com/minibeit/businessprofile/web/BusinessProfileControllerTest.java, backend/src/test/java/com/minibeit/businessprofile/web/BusinessProfileReviewControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostApplicantByBusinessControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostApplicantControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostByBusinessControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java, backend/src/test/java/com/minibeit/post/web/RejectPostControllerTest.java, backend/src/test/java/com/minibeit/school/web/SchoolControllerTest.java, backend/src/test/java/com/minibeit/user/web/AuthControllerTest.java, backend/src/test/java/com/minibeit/user/web/UserControllerTest.java
=> [backend] api 공통 response format 수정

backend/src/main/java/com/minibeit/common/component/file/S3Uploader.java, backend/src/main/java/com/minibeit/common/dto/SavedFile.java, backend/src/rest/AuthController.http, backend/src/rest/UserController.http
=> [backend] 파일 업로드 오류 수정

backend/scripts/profile.sh, frontend/src/utils/common/interceptors.js
=> [backend] 무중단 배포 오류 수정, api 맞춰서 refresh token 수정 

backend/build.gradle, backend/src/docs/asciidoc/index.adoc, backend/src/docs/asciidoc/mail.adoc, backend/src/main/java/com/minibeit/DataLoader.java, backend/src/main/java/com/minibeit/mail/condition/ApproveCancelCondition.java, backend/src/main/java/com/minibeit/mail/condition/ApproveCondition.java, backend/src/main/java/com/minibeit/mail/condition/MailCondition.java, backend/src/main/java/com/minibeit/mail/condition/PostMailCondition.java, backend/src/main/java/com/minibeit/mail/condition/RejectCondition.java, backend/src/main/java/com/minibeit/mail/dto/PostStatusMail.java, backend/src/main/java/com/minibeit/mail/dto/PostStatusMailRequest.java, backend/src/main/java/com/minibeit/mail/service/PostStatusMailService.java, backend/src/main/java/com/minibeit/mail/web/PostStatusMailController.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostApplicantDto.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/main/java/com/minibeit/post/scheduler/PostRejectScheduler.java, backend/src/main/java/com/minibeit/security/oauth/OAuthAttributes.java, backend/src/main/java/com/minibeit/user/domain/User.java, backend/src/main/resources/application.yml, backend/src/main/resources/db/migration/V20210822190459__Create_User_Table.sql, backend/src/main/resources/db/migration/V20211108191600__Add_User_Email_Column.sql, backend/src/rest/MailController.http, backend/src/test/java/com/minibeit/MailTestConfig.java, backend/src/test/java/com/minibeit/ServiceIntegrationTest.java, backend/src/test/java/com/minibeit/mail/web/PostStatusMailControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostApplicantByBusinessControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 알림 기능 구현

backend/src/main/java/com/minibeit/post/domain/PostApplicant.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryImpl.java, backend/src/main/java/com/minibeit/post/service/PostApplicantByBusinessService.java, backend/src/main/java/com/minibeit/post/service/PostByBusinessService.java, backend/src/main/java/com/minibeit/post/service/exception/ExistApprovedApplicantException.java, backend/src/main/java/com/minibeit/post/service/exception/ExistedApplySameTimeException.java, backend/src/rest/BusinessProfileController.http, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/post/service/PostApplicantByBusinessServiceTest.java, backend/src/test/java/com/minibeit/post/service/PostByBusinessServiceTest.java
=> [backend] 모집 승인 추가로직 구현

frontend/src/components/BProfile/BProfileFeedList/BManageModal/index.jsx, frontend/src/components/BProfile/BProfileFeedList/BManageModal/presenter.jsx, frontend/src/components/BProfile/BProfileFeedList/BManageModal/style.jsx
=> [frontend] 비즈니스 프로필 실험자 관리 모달 수정

frontend/src/components/BProfile/BProfileFeedList/BManageModal/index.jsx, frontend/src/components/BProfile/BProfileFeedList/BManageModal/presenter.jsx, frontend/src/constants/API_URLS.js, frontend/src/utils/mailApi.js
=> [frontend] 메일 기능 구현

backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/mail/condition/ApplicantCancelCondition.java, backend/src/main/java/com/minibeit/mail/condition/PostMailCondition.java, backend/src/main/java/com/minibeit/mail/dto/PostStatusMail.java, backend/src/main/java/com/minibeit/mail/dto/PostStatusMailRequest.java, backend/src/main/java/com/minibeit/mail/service/PostStatusMailService.java, backend/src/main/java/com/minibeit/mail/web/PostStatusMailController.java, backend/src/main/java/com/minibeit/post/domain/repository/PostLikeRepository.java, backend/src/main/java/com/minibeit/post/domain/repository/PostLikeRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostLikeRepositoryImpl.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/main/java/com/minibeit/post/scheduler/PostRejectScheduler.java, backend/src/main/java/com/minibeit/post/service/PostApplicantService.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/java/com/minibeit/user/dto/UserResponse.java, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/mail/web/PostStatusMailControllerTest.java, backend/src/test/java/com/minibeit/post/service/PostApplicantServiceTest.java, backend/src/test/java/com/minibeit/post/service/PostServiceTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java, backend/src/test/java/com/minibeit/user/web/UserControllerTest.java
=> [backend] 확정자 취소시 메일 전송 추가 , 즐겨찾기 로직 추가

frontend/src/App.js, frontend/src/components/BProfile/BProfileFeedList/BManageModal/index.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileUserModal/style.jsx, frontend/src/constants/API_URLS.js, frontend/src/pages/ProcessLogin/index.jsx, frontend/src/utils/mailApi.js
=> [frontend] 로그인, 메일 api맞춰 코드 수정

frontend/src/App.js, frontend/src/components/SignUp/SignupForm/InfoData/index.jsx, frontend/src/components/SignUp/SignupForm/index.jsx, frontend/src/components/SignUp/SignupForm/style.jsx, frontend/src/constants/API_URLS.js, frontend/src/pages/ProcessLogin/index.jsx, frontend/src/pages/SignUp/index.jsx, frontend/src/recoil/signupState.js, frontend/src/recoil/userState.js, frontend/src/utils/auth.js, frontend/src/utils/mailApi.js, frontend/src/utils/smsApi.js
=> [frontend] 회원가입 인증 구현

backend/build.gradle, backend/src/main/java/com/minibeit/user/domain/repository/UserVerificationCodeRepository.java, backend/src/main/java/com/minibeit/user/dto/UserResponse.java, backend/src/main/java/com/minibeit/user/service/UserService.java, backend/src/main/java/com/minibeit/user/web/UserController.java, backend/src/test/java/com/minibeit/businessprofile/service/BusinessProfileReviewServiceTest.java, backend/src/test/java/com/minibeit/user/web/UserControllerTest.java
=> [backend] 내정보 조회 , 인증코드 확인 response data 추가

frontend/src/components/ApplyDetail/FeedInfoContainter/presenter.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileEditModal/index.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileEditModal/presenter.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileEditModal/style.jsx, frontend/src/components/Common/Modal/BProfileCreateModal/index.jsx, frontend/src/components/Common/Modal/BProfileCreateModal/presenter.jsx, frontend/src/components/Common/Modal/BProfileCreateModal/style.jsx, frontend/src/components/Profile/UserContainer/UserInfoEditModal/index.jsx, frontend/src/components/Profile/UserContainer/UserInfoEditModal/presenter.jsx, frontend/src/components/Profile/UserContainer/UserInfoEditModal/style.jsx, frontend/src/components/Recruit/BProfileSelect/index.jsx, frontend/src/components/Recruit/BProfileSelect/presenter.jsx, frontend/src/components/Recruit/InfoData/presenter.jsx, frontend/src/components/SignUp/SignupForm/InfoData/index.jsx, frontend/src/components/SignUp/SignupForm/index.jsx
=> [frontend] 회원정보, 게시물 예외처리

frontend/src/components/Profile/UserContainer/FeedBox/index.jsx, frontend/src/components/Profile/UserContainer/index.jsx, frontend/src/components/Profile/style.jsx, frontend/src/components/SignUp/SignupForm/index.jsx, frontend/src/utils/profileApi.js
=> [frontend] 프로필 피드카테고리 순서변경, 즐겨찾기 구현

backend/build.gradle, backend/src/docs/asciidoc/mail.adoc, backend/src/main/java/com/minibeit/config/AsyncConfig.java, backend/src/main/java/com/minibeit/mail/condition/ApplicantCancelPostCondition.java, backend/src/main/java/com/minibeit/mail/condition/ApproveCancelPostCondition.java, backend/src/main/java/com/minibeit/mail/condition/ApprovePostCondition.java, backend/src/main/java/com/minibeit/mail/condition/MailPostCondition.java, backend/src/main/java/com/minibeit/mail/condition/RejectPostCondition.java, backend/src/main/java/com/minibeit/mail/dto/PostStatusMail.java, backend/src/main/java/com/minibeit/mail/service/MailService.java, backend/src/main/java/com/minibeit/mail/web/MailController.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepository.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryImpl.java, backend/src/main/java/com/minibeit/post/service/PostApplicantByBusinessService.java, backend/src/main/java/com/minibeit/post/service/PostApplicantService.java, backend/src/main/resources/templates/applicantApprove.html, backend/src/main/resources/templates/applicantCancel.html, backend/src/main/resources/templates/applicantReject.html, backend/src/main/resources/templates/approveCancel.html, backend/src/main/resources/templates/emailVerification.html, backend/src/rest/MailController.http, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/mail/web/MailControllerTest.java
=> [backend] 이메일 템플릿 맞추기, 메일 비동기로 구현

frontend/public/css/index.css, frontend/src/components/BProfile/BProfileFeedList/BManageModal/presenter.jsx, frontend/src/components/BProfile/BProfileFeedList/BManageModal/style.jsx, frontend/src/components/BProfile/index.jsx
=> [frontend] 참여자관리 모달 디자인 수정, 개인프로필 버튼 링크 수정

backend/src/main/java/com/minibeit/common/dto/ApiResult.java, backend/src/main/java/com/minibeit/mail/condition/ApplicantCancelPostCondition.java, backend/src/main/java/com/minibeit/mail/condition/ApproveCancelPostCondition.java, backend/src/main/java/com/minibeit/mail/condition/ApprovePostCondition.java, backend/src/main/java/com/minibeit/mail/condition/MailPostCondition.java, backend/src/main/java/com/minibeit/mail/condition/RejectPostCondition.java, backend/src/main/java/com/minibeit/mail/dto/PostStatusMail.java, backend/src/main/java/com/minibeit/mail/service/MailService.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostDoDateRepositoryImpl.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostApplicantResponse.java, backend/src/main/java/com/minibeit/post/scheduler/PostRejectScheduler.java, backend/src/main/java/com/minibeit/post/service/PostApplicantByBusinessService.java, backend/src/main/java/com/minibeit/post/service/PostApplicantService.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/main/resources/templates/applicantApprove.html, backend/src/main/resources/templates/applicantCancel.html, backend/src/main/resources/templates/applicantReject.html, backend/src/main/resources/templates/approveCancel.html, backend/src/rest/AuthController.http, backend/src/rest/PostApplicantController.http, backend/src/test/java/com/minibeit/post/service/PostServiceTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 메일 템플릿 추가 적용, 즐겨찾기 목록 필터링 제거

backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/scheduler/PostRejectScheduler.java, backend/src/rest/AuthController.http, backend/src/rest/PostApplicantController.http
=> [backend] 확정목록 리스트 조건 수정, 반려 메일 배치 작업 추가

backend/src/main/java/com/minibeit/post/domain/Post.java, backend/src/main/java/com/minibeit/post/dto/PostRequest.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/main/resources/db/migration/V20211205201206__Add_Column_Post_Table.sql, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/post/web/PostByBusinessControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 주소 상세주소 나눠서 저장하도록 구현

frontend/src/components/ApplyDetail/ApplyController/index.jsx, frontend/src/components/ApplyDetail/FeedInfoContainter/presenter.jsx, frontend/src/components/ApplyDetail/style.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileEditModal/index.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileEditModal/presenter.jsx, frontend/src/components/BProfile/style.jsx, frontend/src/components/Common/Modal/BProfileCreateModal/index.jsx, frontend/src/components/Profile/BusinessContainer/index.jsx, frontend/src/utils/bprofileApi.js, frontend/src/utils/common/interceptors.js
=> [frontend] 비즈니스 프로필 주소, 상세주소 분리

backend/src/docs/asciidoc/file.adoc, backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/minibeit/common/component/file/S3Uploader.java, backend/src/main/java/com/minibeit/config/SecurityConfig.java, backend/src/main/java/com/minibeit/file/web/FileController.java, backend/src/main/java/com/minibeit/post/dto/PostFileDto.java, backend/src/main/java/com/minibeit/review/domain/BusinessUserReview.java, backend/src/main/java/com/minibeit/review/dto/BusinessUserReviewResponse.java, backend/src/main/java/com/minibeit/review/service/BusinessUserReviewService.java, backend/src/main/java/com/minibeit/review/web/BusinessUserReviewController.java, backend/src/rest/FileController.http, backend/src/test/java/com/minibeit/file/web/FileControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java, backend/src/test/java/com/minibeit/review/service/BusinessUserReviewFindServiceTest.java, backend/src/test/java/com/minibeit/review/service/BusinessUserReviewServiceTest.java, backend/src/test/java/com/minibeit/review/web/BusinessUserReviewControllerTest.java
=> [backend] 후기 통합테스트 작성, 파일 다운로드

frontend/src/components/ApplyDetail/FeedInfoContainter/TimeSelectBox/index.jsx, frontend/src/components/ApplyDetail/FeedInfoContainter/TimeSelectBox/presenter.jsx, frontend/src/components/BProfile/BProfileFeedList/BManageModal/index.jsx, frontend/src/components/Common/CalendarButton/index.jsx, frontend/src/components/Profile/UserContainer/FeedBox/index.jsx, frontend/src/components/Profile/UserContainer/index.jsx, frontend/src/components/Recruit/InfoData/presenter.jsx, frontend/src/components/Recruit/style.jsx, frontend/src/constants/API_URLS.js, frontend/src/utils/bprofileApi.js, frontend/src/utils/feedApi.js, frontend/src/utils/index.jsx, frontend/src/utils/profileApi.js
=> [frontend] 프론트 api url 수정

frontend/src/utils/bprofileApi.js
=> [frontend] bp api 수정

backend/src/docs/asciidoc/businessprofile.adoc, backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/businessprofile/service/BusinessProfileService.java, backend/src/main/java/com/minibeit/businessprofile/service/exception/BusinessProfileAdminCantCancelException.java, backend/src/main/java/com/minibeit/businessprofile/web/BusinessProfileController.java, backend/src/main/java/com/minibeit/post/service/PostByBusinessService.java, backend/src/main/java/com/minibeit/post/web/PostByBusinessController.java, backend/src/main/java/com/minibeit/user/web/UserController.java, backend/src/rest/AuthController.http, backend/src/rest/BusinessProfileController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/businessprofile/web/BusinessProfileControllerTest.java, backend/src/test/java/com/minibeit/post/service/PostByBusinessServiceTest.java, backend/src/test/java/com/minibeit/post/service/PostFindServiceTest.java, backend/src/test/java/com/minibeit/post/service/PostServiceTest.java, backend/src/test/java/com/minibeit/post/web/PostByBusinessControllerTest.java, backend/src/test/java/com/minibeit/user/web/UserControllerTest.java
=> [backend] post 생성 api, 파일 추가 api 통합 및 테스트작성, 비즈니스 탈퇴 구현

frontend/src/components/Recruit/InfoData/index.jsx, frontend/src/components/Recruit/InfoData/presenter.jsx, frontend/src/components/Recruit/index.jsx, frontend/src/utils/feedApi.js
=> [frontend] 게시물 생성 api 맞춰 수정 & 이미지 삭제 버튼 수정

backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/dto/PostResponse.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 즐겨찾기 목록 응답 데이터 수정

frontend/src/components/ApplyDetail/ApplyController/index.jsx, frontend/src/components/ApplyDetail/FeedInfoContainter/TimeSelectBox/presenter.jsx, frontend/src/components/ApplyDetail/FeedInfoContainter/presenter.jsx, frontend/src/components/ApplyDetail/index.jsx, frontend/src/components/ApplyDetail/style.jsx, frontend/src/components/Profile/BusinessContainer/index.jsx, frontend/src/components/Profile/UserContainer/UserInfoBox/index.jsx, frontend/src/components/Profile/UserContainer/index.jsx, frontend/src/components/Profile/UserLikeContainer/index.jsx, frontend/src/components/Profile/index.jsx, frontend/src/components/Profile/style.jsx
=> [frontend] 상세게시물 페이지 디자인 수정

frontend/public/css/index.css, frontend/public/css/react-calendar.css, frontend/src/App.js, frontend/src/components/Apply/ListContainer/index.jsx, frontend/src/components/Apply/SearchBar/index.jsx, frontend/src/components/ApplyDetail/TitleContiner/index.jsx, frontend/src/components/ApplyDetail/index.jsx, frontend/src/components/Common/CalendarButton/index.jsx, frontend/src/components/Common/DateInput/index.jsx, frontend/src/components/Common/DateInput/style.jsx, frontend/src/components/Common/Footer/index.jsx, frontend/src/components/Common/Footer/style.jsx, frontend/src/components/Common/index.jsx, frontend/src/components/Recruit/index.jsx, frontend/src/components/RecruitComplete/style.jsx
=> [frontend] 프론트 스타일, 오류 수정

frontend/src/components/Common/NavBar/SideMenu.jsx, frontend/src/components/Common/NavBar/index.jsx, frontend/src/components/Common/NavBar/style.jsx
=> [frontend] 네비게이션바 반응형 추가

backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostApplicantRepositoryImpl.java, backend/src/main/java/com/minibeit/post/service/PostApplicantByBusinessService.java, backend/src/main/java/com/minibeit/post/service/dto/PostApplicantDto.java, backend/src/main/java/com/minibeit/post/service/dto/PostApplicantResponse.java, backend/src/rest/PostApplicantController.http, backend/src/test/java/com/minibeit/post/web/PostApplicantByBusinessControllerTest.java
#405 
java stream groupingby 제거, querydsl transform 사용
=> [backend] 게시물에 해당하는 지원자 목록 조회 리펙토링

backend/src/docs/asciidoc/post.adoc, backend/src/main/java/com/minibeit/businessprofile/domain/repository/BusinessProfileRepositoryCustom.java, backend/src/main/java/com/minibeit/businessprofile/domain/repository/BusinessProfileRepositoryImpl.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryCustom.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/post/service/PostByBusinessService.java, backend/src/main/java/com/minibeit/post/service/PostService.java, backend/src/main/java/com/minibeit/post/service/dto/PostResponse.java, backend/src/main/java/com/minibeit/post/web/PostByBusinessController.java, backend/src/main/java/com/minibeit/post/web/PostController.java, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/test/java/com/minibeit/post/service/PostByBusinessFindServiceTest.java, backend/src/test/java/com/minibeit/post/web/PostByBusinessControllerTest.java, backend/src/test/java/com/minibeit/post/web/PostControllerTest.java
=> [backend] 개인 프로필 신청현황, 비즈니스 프로필 공고현황

backend/src/main/java/com/minibeit/common/utils/CryptoConverter.java, backend/src/main/java/com/minibeit/user/domain/User.java, backend/src/main/resources/dev-file-debug-aws-appender.xml, backend/src/main/resources/dev-file-error-aws-appender.xml, backend/src/main/resources/dev-file-info-aws-appender.xml, backend/src/main/resources/dev-file-warn-aws-appender.xml, backend/src/main/resources/file-debug-aws-appender.xml, backend/src/main/resources/file-info-aws-appender.xml, backend/src/main/resources/file-warn-aws-appender.xml, backend/src/main/resources/logback-spring.xml, backend/src/test/java/com/minibeit/user/service/UserServiceTest.java, backend/src/test/resources/application.yml
=> [backend] 개인정보 암호화, 로그 그룹 추가

frontend/src/components/BProfile/BProfileFeedList/BManageModal/presenter.jsx, frontend/src/components/BProfile/BProfileInfo/BProfileUserModal/index.jsx, frontend/src/components/BProfile/style.jsx, frontend/src/components/Common/Alert/AskAttendance/index.jsx, frontend/src/components/Common/Alert/AskCancelConfirm/index.jsx, frontend/src/components/Common/Alert/CancleAttend/index.jsx, frontend/src/components/Common/Alert/DeleteBProfile/index.jsx, frontend/src/components/Common/Pagination/index.jsx, frontend/src/components/Profile/BusinessContainer/index.jsx, frontend/src/components/Profile/UserContainer/FeedBox/index.jsx, frontend/src/components/Profile/style.jsx, frontend/src/utils/bprofileApi.js
=> [frontend] 프론트 오류 수정

backend/src/main/java/com/minibeit/review/domain/BusinessUserReview.java, backend/src/main/java/com/minibeit/review/service/BusinessUserReviewService.java, backend/src/rest/BusinessProfileReviewController.http, backend/src/rest/PostApplicantController.http, backend/src/test/java/com/minibeit/review/service/BusinessUserReviewFindServiceTest.java
=> [backend] 비즈니스 프로필에 대한 리뷰 생성 오류 수정

frontend/src/components/BProfile/index.jsx, frontend/src/components/Common/Pagination/index.jsx, frontend/src/components/Profile/UserContainer/CreateReviewModal/index.jsx, frontend/src/components/Profile/UserContainer/index.jsx
=> [frontend] 리뷰 create 수정 & 프로필, 비즈니스 프로필 뷰 수정

frontend/src/components/Profile/index.jsx
=> [frontend] 비즈니스 프로필 페이지 안들어가지는 오류 수정

backend/src/main/java/com/minibeit/post/domain/PostApplicant.java, backend/src/main/java/com/minibeit/post/domain/repository/PostRepositoryImpl.java, backend/src/main/java/com/minibeit/school/domain/SchoolRepository.java, backend/src/main/java/com/minibeit/school/service/SchoolService.java, backend/src/main/resources/db/migration/V20220108200451__update_school.sql, backend/src/rest/PostApplicantController.http, backend/src/rest/PostController.http, backend/src/rest/SchoolController.http, backend/src/test/java/com/minibeit/school/service/SchoolServiceTest.java
=> [backend] 개인프로필에서 확정 완료 게시물 목록 조회 수정, 모집 위치무관 추가
